[tool.poetry]
name = "laika-project-ai"
version = "0.1.0"
description = ""
authors = ["Bego"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
ollama = "^0.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

